steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/football-fixtures', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/football-fixtures']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'football-fixtures'
  - '--image'
  - 'gcr.io/$PROJECT_ID/football-fixtures'
  - '--region'
  - 'europe-west2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '2Gi'
  - '--set-env-vars'
  - 'FLASK_ENV=production'
  - '--set-secrets'
  - 'DATABASE_URL=DATABASE_URL:latest,SECRET_KEY=SECRET_KEY:latest,GOOGLE_OAUTH_CLIENT_ID=GOOGLE_OAUTH_CLIENT_ID:latest,GOOGLE_OAUTH_CLIENT_SECRET=GOOGLE_OAUTH_CLIENT_SECRET:latest'
images:
- 'gcr.io/$PROJECT_ID/football-fixtures'
